# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190219_2213'),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='login_app.register'),
            preserve_default=False,
        ),
    ]
